chore: lock sm's sm_cargo dependency to 0.6.x
This is required to publish to crates.io:

    error: all path dependencies must have a version specified when publishing.
    dependency `sm_macro` does not specify a version

And is a good practice in general.

Going forward, this should be updated whenever a
breaking change is introduced, or a new minor version
is released.